name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --tests -- -D warnings -W clippy::dbg_macro

      - name: Cargo test+build
        run: cargo test --release && cargo build --release
        env:
          OPENSSL_STATIC: "1"
          OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu/
          OPENSSL_INCLUDE_DIR: /usr/include/openssl

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests -s -vvv
        timeout-minutes: 5

      - name: Publish (dry run)
        run: cargo publish --dry-run
        if: github.ref != 'refs/heads/master'

      - name: Publish on crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
        if: github.ref == 'refs/heads/master'
